#!/bin/bash

for i in 'more usernames.txt'
do
echo $i
echo $i"123" | passwd "$i" --stdin
sudo useradd -m -d /home/$i | cat > welcom.txt > Welcome new user
echo; echo "$i passowrd is has been changed"
done
